---
- name:   9k facts
  hosts:    Nexus_OS
  connection: local 
  tasks: 
      - name: Get Nexus9k facts
        nxos_fatcs:
              host: "{{inventory_hostname}}''
              transport: nxapi
              use_ssl:yes
              validate_certs: no
        register:nxos_data

      - name: Print name to console
        debug: msg="{{nxos-data}}"